### PR TITLE
add ability to change inactive/unselected item bordercolor

### PR DESCRIPTION
**Pull request by inkeso**
Just a small patch for even more visual customizability
alttab-vertical

This probably addresses #95

### CODE REVIEW

**Comment by sagb** [comment]
Sorry, it's inconvenient to pull "all or nothing" of these changes.
Could you please create a distinct branch with 10ce604884099e3553d964de908525ae5ac84ea2 only, and in the PR use this branch instead of master?
Please ask for help if needed. Thank you.

**Comment by inkeso** [comment]
OK, I made a new PR: https://github.com/sagb/alttab/pull/132 
...is this the right way to handle this? I didn't find a way to change this PR.

**Comment by sagb** [comment]
Thank you, it's ok.

**Comment by sagb** [comment]
What is the point to skip dock windows? What window in what WM do you intend to hide?

**Comment by inkeso** [comment]
I'm using JWM and xfce4-panel. If i remeber correctly, the same does happen with pekwm:
If I'm using your version, xfce4-panel is not in the window list, which is correct. But sticky windows aren't neither.

So i changed that one line in ewmh.c. Now sticky windows appear in tasklist (as they should, at least in my usecase), but so does xfce4-panel... the panel sets _NET_WM_WINDOW_TYPE_DOCK. But it also is sticky, so your version hides it correctly...

**Pull request closed without merging**
