### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by abdulrafaykhan**

### CODE REVIEW

**Comment by abdulrafaykhan** [comment]
Hey @sagb 

I believe you closed this PR and did not approve it 

Can I ask where do you feel the PR was lacking ? 

I am a newbie to the development scene and would appreciate constructive feedback :) 

Thank you !

**Comment by sagb** [comment]
You wanted to merge some stub file, probably unrelated to this project, for unclear reason, without any comment.

**Comment by sagb** [comment]
Wyy do you think alttab needs this?

**Comment by abdulrafaykhan** [comment]
Well for one it does ask for screen recording permissions in MacOS which requires sudo privilege. Some companies might want to review the security posture of the application before allowing it in their environment

Also, there is no documentation regarding if there are any security bugs

So this seems like a good first step in that direction

**Comment by sagb** [comment]
Thank you for your effort, but I don't want this. Consider alttab insecure and never run it as root.

**Pull request closed without merging**
