### PR TITLE
add OpenBSD instructions for building from source

### PR DESCRIPTION
**Pull request by Veraellyunjie**
Please note that `m4` is not required for the described route
Please note that [`make check` fails](https://github.com/sagb/alttab/issues/143#issuecomment-1331499392), yet `alttab` seems to work fine

### CODE REVIEW

**Comment by sagb** [comment]
I included checks for autotools version in bootstrap.sh and fixed INSTALL.md accordingly.
Please check:
1. does `bootstrap.sh` succeed without specifying any environmental variable?
2. same for `make`?

**Comment by Veraellyunjie** [comment]
> 1. does `bootstrap.sh -f` succeed without specifying any environmental variable?
`bootstrap.sh` does succeed.
`bootstrap.sh -f` — dunno. `ronn` is not installed, and although [package tracker says there is such a package](https://openports.se/textproc/ruby-ronn) from 2011 and a maintenance commit in 2019, when I `pkg_add ruby-ronn` it says:
```
Can't find ruby-ronn
Obsolete package: ruby-ronn (no longer maintained upstream)
```
I also don't use `ruby` and its `gem`s and [`gem` package doesn't seem to exist](https://openports.se/search.php?so=gem).
But, if you think `ronn` is crucial, then tell me, I'll explore how to install it and test `bootstrap.sh -f`

> 2. same for `make`?
No, `make` needs both.
```
> make
...
Provide an AUTOCONF_VERSION environment variable, please
...
```
```
> CPATH=/usr/local/include make
...
Provide an AUTOCONF_VERSION environment variable, please
...
```

**Comment by sagb** [comment]
Your changes are OK.
I hoped to deal with autotools versions in bootstrap.sh automatically, without any mention in docs (uthash is another story).
Are you sure that after the following make still wants AUTOCONF_VERSION?

make distclean
./bootstrap.sh -f (to run autoreconf with -f)
./configure
CPATH=/usr/local/include make

**Comment by Veraellyunjie** [comment]
```
> ./configure
...
configure: error: Cannot find uthash.h, please install uthash
```
```
> CPATH=/usr/local/include ./configure  # OK
```
I didn't highlight `CPATH=/usr/local/include ./configure` in the last comment since you didn't ask, but you can't use it bare.

---

> 1. does `bootstrap.sh -f` succeed without specifying any environmental variable?
>
> Are you sure that after the following make still wants AUTOCONF_VERSION?
> ./bootstrap.sh -f (to run autoreconf with -f)

Sorry, last time there [was](https://github.com/sagb/alttab/pull/144/commits/8471d98ccd656017f5533c8ec73c71075d2c43bc) an error `which: ronn: Command not found.` — I got confused and took this minor error for an overall `bootstrap.sh` failure and didn't check steps after `./bootstrap.sh -f`. Ran whole thing with `./bootstrap.sh` without `-f`.  
Good you are attentive and asked again.
You are right, after `./bootstrap.sh -f`:  
`CPATH=/usr/local/include make` without `AUTOCONF_VERSION` is enough

---

About the next commit:
AFAIK, typically, manual invocation with `-h`elp should print to STDOUT and `exit 0`, as it is what user explicitly requests.  
STDERR and `exit 1` is for when user invokes executable with wrong arguments.

**Comment by Veraellyunjie** [comment]
Thank you, @sagb, you are very helpful and pleasant to work with.  
Happy alt-tabbing!

**Pull request merged**
