### PR TITLE
Backward prev next

### PR DESCRIPTION
**Pull request by roboshim**
Dear sagb,

I work in WindowMaker and colleague told me to test i3. I have already tested i3, but I have found, I am missing Alt-TAB feature from WindowMaker to switch between last recent window. I use this feature most of all. So I have found your alttab, which works perfect in i3 too.

But I use another two features of Alt-TAB in WindowMaker .

1. I switch recent window using Alt-TAB. I know, alttab has Alt+Shift+TAB feature for backward switch, but (a) in WindowMaker I use Alt+Shift+TAB to switch between the same windows (e.g. starting Alt+Shift+Tab in XTerm selects Xterms only and skips other windows), (b) I have configured Ctrl+TAB to start and go through windows in reverse order, i.e. the first selected window is the last window and using Ctrl+TAB/Release, Ctrl+TAB/Release, ... I can go through all windows easily.

2. If I start window switching, I can use in WindowMaker keys Left and Right to go through the list Left and Right and exactly select desired window. I know, I could use Alt+TAB got switch next window and use Alt+Shift+TAB to get to previous, but Alt+Shift+TAB is more complicated to press then Left and Right.

I have found your alttab perfect for my needs so I have decided to implement the other two features from WindowMaker app switcher.

I am no real C programmer, I can code in bash, perl and some other languages, but mostly some light scripts only.

I have read your code and tried to add additional code according to your current code. I have tried to make as less code changes as possible, but maybe some parts could be now rewritten better (I don't know). If you want to merge my code to your repo, please, read my changes carefully, if they are without bugs, I am really not sure, if my code is good.

I have tested my code and it worked on Debian Stretch with i3 and on Gentoo with WindowMaker:-). I hope there is no problem on other distros and window managers.

Could you please merge my code to get these features directly from your git repo?

The alttab.1 man page must be regenerated from alttab.1.ronn.

Thank you very much.

Regards.

Robert.

### CODE REVIEW

**Comment by sagb** [comment]
Thank you for this great effort.
It's a pity that you didn't separate (1) and (2) in different pull requests.
(2) is definitely ok, but (1) makes things so complicated and grabs Ctrl-Tab by default for the rarely used feature. Btw, Ctrl-Tab is widely used nowadays in web browsers and probably in other multitab software for switching tabs. I'll think a little bit later how to incorporate your work. Thank you anyway!

**Comment by sagb** [comment]
Just in case, you probably know that:
* you can run two alttab processes: one for Alt-Tab and another for Ctrl-Tab (alttab -mk Control_L), perhaps such combo would be able to emulate (1) to some extent
* you can use mouse wheel for the same function as Left-Right keys in your patch

**Comment by roboshim** [comment]
Hello sagb,

I have thought about separating both "features", but I wasn't sure, if I would be able to merge both commits together or only one of them. They both change code at same place (in the main while()), so I was not sure, if git is so good to be able to merge both changes individually. As I have written, I am no developer, I have only little experiences with git and github, there I was happy to make these features running without core dumps:-)

(1)
> is definitely ok

OK, thank you.

(2) 

> makes things so complicated

what do you exactly mean? The code is more complicated, correct, because it starts and runs app switcher in different listing, it must check both shortcuts, it has to remember, which shortcut was starting switcher.

I thought about rewriting somehow the code to simplify it with alt+tab and ctrl+tab, but I was not sure, if you would accept it if there would be many lines changed only for "make it less complicated" (and I am even not sure, if I could do it less complicated).

> Ctrl-Tab is widely used nowadays in web browsers

oh, hmmm, I use it for long time for switch app panel, and I use ctrl+pageup/pagedown for browser tab switching. OK, this conflict is not good:( I have thought I will make these my changes only as patch for Gentoo's ebuild for your original code, but I thought, maybe someone could use it too. Maybe it would be possible to set some less used modifier instead of control by default and then I could set CTRL for my installation.

> you can run two alttab processes: one for Alt-Tab and another for Ctrl-Tab

I didn't know, I can start two alttab, but it would not solve my needs, because -mk is main modifier (switching the most recent apps), but my -rk is reverse main modifier (which starts reverse/backwards listing, same as alt+shift+tab). I.e. if I would start alttab -mk Control_L then ctrl+tab would switched most recent apps again as alt+tab. But my -rk goes in the list from the least used app (the last one app in the list).

> you can use mouse wheel

with mouse I can even click on the app, this is fine. But you know, I use the keyboard shortcut to be able to fast switch between apps without mouse:-) My colleague use "follow mouse focus" in i3 - I don't like this feature. I switch focus either clicking with mouse or using alt+tab. Sometimes I support some users, who switche apps everytime by clicking on taskbar in MS Windows. It makes me crazy - they write something on keyboard, then they want switch second recent app, so they search mouse with eyes, take mouse in the hand, go to taskbar to find app, click, then hand back to keyboard, write something, then again hand on mouse, find the button for the desired app on taskbar, click and hand again on keyboard :-< It's faster to switch two recent apps using alt+tab! :-D


Should I try to separate these changes or do you want accept it as one change? I could try it, maybe it would really be better.

Regards,

Robert.

**Comment by sagb** [comment]
> > (2) makes things so complicated

> what do you exactly mean? 

You change too much for rarely demanded feature, this would bring bugs and instability if enabled by default.

Well, forget about separating the patch, let's merge everything at once.
What is important is to make (1) disabled by default, like `-rk VoidSymbol` by default, and then something like if/else blocks: `if rk==VoidSymbol then old behaviour else new`.
If it looks tiresome, let's do it together in [your repository](https://github.com/roboshim/alttab). Start with your current version, I'll probably commit too, and so we'll prepare the final patch.

Btw, it would be handy it you commit by small chunks instead of giant commit like this merge request)

(2) is ok by default.

**Comment by sagb** [comment]
Oh, by "(1)" I mean your first feature (ctrl-tab), and "(2)" is your second feature (left-right).

**Comment by roboshim** [comment]
> > what do you exactly mean?
> 
> You change too much for rarely demanded feature, this would bring bugs and instability if enabled by default.

OK, I see know, what you mean.

> Well, forget about separating the patch, let's merge everything at once.

Hmmm, maybe it would be really better to make more commits to be clear, what it does and separate it. If you don't hurry, give me little time and I try to split them.

> What is important is to make (1) disabled by default, like `-rk VoidSymbol` by default, and then something like if/else blocks: `if rk==VoidSymbol then old behaviour else new`.
> If it looks tiresome, let's do it together in [your repository](https://github.com/roboshim/alttab). Start with your current version, I'll probably commit too, and so we'll prepare the final patch.

OK, I will try to do it again better:-)

> Btw, it would be handy it you commit by small chunks instead of giant commit like this merge request)

Oh, I thought, it is small patch:-( I thought, one commit should contain working code. Do you mean, I should rather commit every single logic change in single file? I.e. new option description in alttab.1.ronn or new #define in alttab.h? I would like to do it correctly.

Regards,

Robert.

**Comment by roboshim** [comment]
Dear sagb,

I would like to rewrite my changes, but I would like to rewrite it to your satisfaction. Could you please tell me, how would you like to have the conditions?

Do you want to write "simple/single" conditions with duplicated function calls:

```
if (COND1) {
    uiNextWindow();
} else if (COND2) {
    uiPrevWindow();
} else if (COND3) {
    uiPrevWindow();
} else if (COND4) {
    uiNextWindow();
}
```


Or do you want better one more complex condition for every unique function call?

```
if (COND1a || COND1b || COND1c) {
    uiNextWindow();
} else if (COND2a || COND2b || COND3b) {
    uiPrevWindow();
}
```

I have created new branches "left-right" and "backward" in my repo, "backward" is still master, but in "left-right" I have already commited the changes. I have commited every single change - it this how you wanted me to commit changes or is it now to many commits?:-)

Would you look to commit https://github.com/roboshim/alttab/commit/9d5114020afd68934bbe06f28d3120542493dcad if you like this "conditioning style"?

Thank you for your answer.

Regards,

Robert.

**Comment by roboshim** [comment]
Dear sagb,

I have created now the branch "backward" with only reverse/backward start key combination. Default is VoidSymbol for reverse key.

Could you please check both "left-right" and "backward" branches, if they are correctly created and commited?

If both branches are OK for you, I would create two separate pull requests and you can close this pull request.

Regards,

Robert.

**Comment by roboshim** [comment]
Hello sagb,

I have created new branch left-right-backward in my repo, which is fast-forward merge of branch left-right to master and then I have merged branch backward to this branch left-right-backward and I had to resolve conflicts.

Should I request a pull from the newest branch left-right-backward or do you want rather create to separate pull requests, one for each branch/feature (left-right and backward) and then resolve conflicts yourself?

Thank you for answer.

Regards,

Robert.

**Comment by sagb** [comment]
Use any number of commits and any number of pull requests (though I would prefer pull requests which are ready to merge). I just suggested to separate commits logically into feature 1 and feature 2, but this is not mandatory.
https://github.com/roboshim/alttab/commit/9d5114020afd68934bbe06f28d3120542493dcad is ok.
Just make the entire "-rk" (ctrl-tab) feature non-default.

**Comment by roboshim** [comment]
> Use any number of commits and any number of pull requests (though I would prefer pull requests which are ready to merge).

OK.

> I just suggested to separate commits logically into feature 1 and feature 2, but this is not mandatory.

This sound logical. But, only one feature can be merged without conflicts to master. The second feature will every generates some conflicts during merge to master+first-feature.

So I have now branches "left-right" and "backward" based on master, which can be either one or other merged to master with fast-forward merge.

But trying to merge the other feature to new master will generate conflicts, which must be solved manually.

I have already solved these conflicts manually in branches:

* left-right-backward: this is master branch with left-right branch fast-forward merged and then is merged backward branch as one commit.

* left-right-backward-hist: this is master branch with left-right branch fast-forward merged and then every single commit from backward branch is merged with conflicts resolution.


> Just make the entire "-rk" (ctrl-tab) feature non-default.

And one more question. What do you mean to make it non-default?

Do you mean to set unused/empty key modifier only (i.e. #define DEFRMODKS   XK_VoidSymbol) and let the code as is ```if (ev.xkey.state & ( g.option_backMask | g.option_rModMask ))``` etc

Or do you mean to define DEFRMODKS as XK_VoidSymbol but to rewrite the code using following conditions?

```
if (g.option_rModCode == XK_VoidSymbol) {
  original code
} else {
  new code
}
```

Thank you for you answers.

Regards.

Robert

**Comment by ykaliuta** [comment]
> > Use any number of commits and any number of pull requests (though I would prefer pull requests which are ready to merge).
> 
> OK.
> 
> > I just suggested to separate commits logically into feature 1 and feature 2, but this is not mandatory.
> 
> This sound logical. But, only one feature can be merged without conflicts to master. The second feature will every generates some conflicts during merge to master+first-feature.

So it's just 2 commits in one pull request.

**Comment by ykaliuta** [comment]
@roboshim Please, be more verbose in your commit messages: "what you are doing". "Why, how and why this way" if it is not obvious from the patch itself.

**Comment by sagb** [comment]
@roboshim, I'm very sorry, but please suspend your adaptation effort for "ctrl-tab" (backward) feature. I decided to not merge it into master at all.

Also, I was going to merge your "left-right" version, but realized that you _grabbed_ `alt-left` and `alt-right`. Why you do this? X11 grab is powerful and invasive action, so grabbing Alt-Tab is *enough*. I thought about the following: user presses Alt-Tab, GUI appears, and then he may use Left and Right keys, in exactly the same way as mouse wheel. Does this sound reasonable for you or you prefer to use Alt-Left immediately, without pressing Alt-Tab?

**Comment by roboshim** [comment]
@ykaliuta Hello.

> So it's just 2 commits in one pull request.

This pull request from backward-prev-next is one big commit, but I think you should reject this pull request.

Then I have created other branches, for every feature one, with every change as signle commit (branches and left-right), both based on master.

Then, I have created other branch left-right-backward with ff left-right merge (with every commit history) and then I have manually merged and resolved the conflicts from backward branch, but it was merged as one big commit.

Then, I have created other branch left-right-backward-hist with ff left-right merge (with every commit history) and then I have manually merged every single commit and resolved the conflicts from backward branch.

Sorry, I'm no developer. I have created the other branches with commit and description for every single change, which is mostly single line (see https://github.com/roboshim/alttab/commits/left-right and https://github.com/roboshim/alttab/commits/backward). Are these commits and comments OK for you? If not, I can make new single commits for every feature. I still ask because I just want you both are happy with the commits:-)

@sagb 

> > if (g.option_rModCode == XK_VoidSymbol) {
>
> This one, please, where possible.

OK, then I change the code.

> I'm very sorry, but please suspend your adaptation effort for "ctrl-tab" (backward) feature. I decided to not merge it into master at all.

You don't have to apologize:-) It's your code, you can decide what do you want to merge:-) I keep my code in my repo and will use my repo in my ebuild with ctrl-tab (reverse start). I want it to use and I have just offered to you as open source (I really like your alttab and I wanted to give something back to OSS:-)). I thought someone else could like it too. But you are right, the ctrl-tab is used in browsers and maybe I am only one person using it, even only one person starting "alttab panel" at last window:-) I'm weird person:-)


> Also, I was going to merge your "left-right" version, but realized that you
> grabbed alt-left and alt-right. Why you do this? X11 grab is powerful and
> invasive action, so grabbing Alt-Tab is enough. I thought about the
> following: user presses Alt-Tab, GUI appears, and then he may use Left and
> Right keys, in exactly the same way as mouse wheel. Does this sound
> reasonable for you or you prefer to use Alt-Left immediately, without
> pressing Alt-Tab?

Of course, I can (try to) change it! I write still I am no developer:-) I thought I have to grab these keys too. So I try to change the code for left-right not to grab this keys, but maybe if I will be unable to do it, I would request for your help. Thank you.

Regards,

Robert.

**Pull request merged**
