### PR TITLE
Zero the initial icon_dirs

### PR DESCRIPTION
**Pull request by sgraf812**
The current program exhibits UB.

### CODE REVIEW

**Comment by ykaliuta** [comment]
--- a/src/icon.c
+++ b/src/icon.c
@@ -153,7 +153,7 @@ int allocIconDirs(char ** icon_dirs)
             id2[id2len - 1] = '\0';
             // search for duplicates
             int idsd;
-            for (idsd = 0; icon_dirs[idsd] != NULL; idsd++) {
+            for (idsd = 0; idsd < idndx; idsd++) {
                 if (strncmp (icon_dirs[idsd], id2, id2len) == 0) {
                     msg(1, "skip duplicate icon dir: %s\n", id2);
                     free(id2); id2 = NULL;

can be a bit more reasonable

**Comment by sgraf812** [comment]
Sure, but I don't think that should happen as part of this PR?

**Comment by ykaliuta** [comment]
> Sure, but I don't think that should happen as part of this PR?

Instead, 'cause the initialization is not necessary then.

**Comment by sgraf812** [comment]
Ah, yes. That would probably work, but just zeroing it is the safer and more future-proof default, no? Anyway, it's your choice.

**Comment by sagb** [comment]
Thank you for pointing out to the bug, though @ykaliuta is right: the code just should not rely on zero in the structure in the middle of building it.

**Pull request closed without merging**
