### PR TITLE
vertical list option

### PR DESCRIPTION
**Pull request by jj1uzh**
Thank you for your work.
This PR implements #76 .

- [x] readme,manual
- [x] test

### CODE REVIEW

**Comment by sagb** [comment]
Cool. It's so crazy to see it vertical.

**Comment by sagb** [comment]
It obviously will not break horizontal usage, because you preserved every calculation for horizontal layout. For vertical usage it lacks testing in multihead configuration, let us name it "experimental" in documentation.

**Comment by sagb** [comment]
Would you prefer to fix documentation by yourself or I will?

**Comment by jj1uzh** [comment]
Could you please fix docs?
`-vertical` option takes no values.
Usage example: `alttab -i 128x128 -vertical -t 1024x128 ...`

**Comment by jj1uzh** [comment]
Should I add any tests for this feature?

**Comment by sagb** [comment]
> Should I add any tests for this feature?

Save your time, current test script test/run-in-xvfb.test is very simple and doesn't test for many dangerous corner cases, not to mention different layouts.

**Comment by pglira** [comment]
Thank you for this new features - it works great!

One nice addition would be to left align the text (instead of centered text), so that it starts next to the icon.

**Comment by inkeso** [comment]
Here is a patch for that:
[vertical-left-align.patch.txt](https://github.com/sagb/alttab/files/7777367/vertical-left-align.patch.txt)
(not sure if this is the best or correct way to do that, but it works)

**Pull request merged**
